# docker-compose file to setup:
# - mysql
# - elasticsearch
# - backend: depends on mysql and elasticsearch
# - frontnend: depends on backend

# This file is meant to aid local development and testing. It *must not* be
# used for production deployment.

version: "3.5"

services:

  mysql:
    container_name: bioagents-mysql
    image: mysql:8.0.23
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=iechorroot
      - MYSQL_DATABASE=iechor
      - MYSQL_USER=iechor
      - MYSQL_PASSWORD=123
    volumes:
      - "data-mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net

  elasticsearch:
    container_name: bioagents-elasticsearch
    image: elasticsearch:7.12.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - "data-elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net
      
  backend:
    container_name: bioagents-backend
    image: bioagents/backend:latest
    build:
      context: ./backend
    environment:
      - BIOTOOLS_ELASTIC_SEARCH_URLS=http://elasticsearch:9200
      - BIOTOOLS_MYSQL_DB=iechor
      - BIOTOOLS_MYSQL_HOST=mysql
      - BIOTOOLS_MYSQL_PASSWORD=123
      - BIOTOOLS_MYSQL_USER=iechor
    ports:
      - "8000:80"
    networks:
      - net
    depends_on:
      - mysql
      - elasticsearch
    links:
      - mysql
      - elasticsearch
    volumes:
      - ./backend:/iechor/application/backend:consistent
      - ./frontend:/iechor/application/frontend

  # dockerfile in frontend dir
  frontend:
    container_name: bioagents-frontend
    image: bioagents/frontend:latest
    build:
      context: ./frontend
    networks:
      - net
    depends_on:
       - backend
    volumes:
      - ./frontend:/home/bioagents/frontend:consistent
      - bioagents_node_modules:/home/bioagents/frontend/node_modules
      - bioagents_bower_components:/home/bioagents/frontend/bower_components


networks:
  net:
    name: bioagents-net

volumes:
  data-mysql: {}
  data-elasticsearch: {}
  bioagents_node_modules: {}
  bioagents_bower_components: {}
