version: "3.7"

services:
  mysql:
    container_name: bioagents-mysql
    image: mysql:8.0.23
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=iechor
      - MYSQL_USER=iechor
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "data-mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  elasticsearch:
    container_name: bioagents-elasticsearch
    image: elasticsearch:7.12.1
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - "data-elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"]
      interval: 1m
      timeout: 20s
      retries: 3
      start_period: 40s

  backend:
    container_name: bioagents-backend
    build:
      context: ./backend
      args:
        - ENV=production
    environment:
      - BIOTOOLS_ELASTIC_SEARCH_URLS=http://elasticsearch:9200
      - BIOTOOLS_MYSQL_DB=iechor
      - BIOTOOLS_MYSQL_HOST=mysql
      - BIOTOOLS_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - BIOTOOLS_MYSQL_USER=iechor
    ports:
      - "8000:80"
    networks:
      - net
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./backend:/iechor/application/backend:ro

  frontend:
    container_name: bioagents-frontend
    build:
      context: ./frontend
      args:
        - ENV=production
    networks:
      - net
    depends_on:
      - backend
    volumes:
      - ./frontend:/home/bioagents/frontend:ro

networks:
  net:
    name: bioagents-net

volumes:
  data-mysql: {}
  data-elasticsearch: {}